[package]
name = "message_passing"
version = "0.1.0"
authors = ["jammin-ben <benjamin.reber19@houghton.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam= "0.7"
thread-id= "4.0.0"
